name: cami_lab
description: CAMILAB 프로젝트
version: 1.0.0+1

# `flutter pub publish`를 사용하여 패키지가 실수로 pub.dev에 게시되는 것을 방지함.
publish_to: none
homepage: https://cami.kr/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
dependencies:
  # 특정 경계에 딱 맞게 자동으로 텍스트 사이즈를 조절할 수 있는 AutoSizeText 위젯
  auto_size_text: ^3.0.0
  # 온라인 이미지를 표시하고 캐싱하는 플러그인
  cached_network_image: ^3.2.3
  # 인피니티 스크롤과 커스텀 차일드 위젯을 쉽게 쓸 수 있는 캐러셀 위젯
  carousel_slider: ^4.2.1
  # 네트워크 연결 상태 플러그인
  connectivity_plus: ^5.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # 플러터 SVG 렌더러
  flutter_screenutil: ^5.9.0
  # 플러터 SVG 렌더러
  flutter_svg: ^2.0.7
  # 의존성 주입 모듈
  get_it: ^7.6.4
  # 구글 폰트
  google_fonts: ^6.1.0
  # 하이브 (크로스플랫폼 NoSQL DB)
  hive_flutter: ^1.1.0
  # Riverpod 훅
  hooks_riverpod: ^2.4.4
  intl: any
  # [Dart] 가독성 좋은 로그 작성을 도와주는 로깅 도구
  logger: ^2.0.2+1
  # 프로바이더 (상태관리)
  provider: ^6.0.5
  # 온보딩 스크린 등에 많이 쓰는 페이지 인디케이터
  smooth_page_indicator: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
flutter:
  # 머티리얼 아이콘 폰트가 애플리케이션에 포함되어 있는지 확인하여 머티리얼 아이콘 클래스에서 아이콘을 사용할 수 있도록 함.
  uses-material-design: true
  # 애플리케이션에 에셋을 추가하려면 다음과 같이 에셋 섹션을 추가함:
  assets:
    - .env
    - assets/images/
    - assets/svg/
  fonts:
    - family: Poppins
      # https://fonts.google.com/specimen/Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: NanumSquare Neo
      # https://hangeul.naver.com/font/nanum
      fonts:
        - asset: assets/fonts/NanumSquareNeo-Bold.ttf
        - asset: assets/fonts/NanumSquareNeo-ExtraBold.ttf
        - asset: assets/fonts/NanumSquareNeo-Heavy.ttf
        - asset: assets/fonts/NanumSquareNeo-Light.ttf
        - asset: assets/fonts/NanumSquareNeo-Regular.ttf
