name: cami_lab
description: CAMILAB 프로젝트
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
dependencies:
  # 온라인 이미지를 표시하고 캐싱하는 플러그인
  cached_network_image: ^3.2.3
  # 인피니티 스크롤과 커스텀 차일드 위젯을 쉽게 쓸 수 있는 캐러셀 위젯
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # 플러터 SVG 렌더러
  flutter_svg: ^2.0.7
  intl: any
  # 프로바이더 (상태관리)
  provider: ^6.0.5
  # 온보딩 스크린 등에 많이 쓰는 페이지 인디케이터
  smooth_page_indicator: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  # 다음 줄은 머티리얼 아이콘 폰트가 애플리케이션에 포함되어 있는지 확인하여 머티리얼 아이콘 클래스에서 아이콘을 사용할 수 있도록 함.
  uses-material-design: true
  # 애플리케이션에 에셋을 추가하려면 다음과 같이 에셋 섹션을 추가함:
  assets:
    - .env
    - assets/images/
    - assets/svg/
  fonts:
    - family: Poppins
      # https://fonts.google.com/specimen/Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: NanumSquare Neo
      # https://hangeul.naver.com/font/nanum
      fonts:
        - asset: assets/fonts/NanumSquareNeo-Bold.ttf
        - asset: assets/fonts/NanumSquareNeo-ExtraBold.ttf
        - asset: assets/fonts/NanumSquareNeo-Heavy.ttf
        - asset: assets/fonts/NanumSquareNeo-Light.ttf
        - asset: assets/fonts/NanumSquareNeo-Regular.ttf
