name: cami_lab
description: CAMILAB 프로젝트
version: 1.0.0+1

# `flutter pub publish`를 사용하여 패키지가 실수로 pub.dev에 게시되는 것을 방지함.
publish_to: none
homepage: https://cami.kr/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
dependencies:
  # 특정 경계에 딱 맞게 자동으로 텍스트 사이즈를 조절할 수 있는 AutoSizeText 위젯
  auto_size_text: ^3.0.0
  # 온라인 이미지를 표시하고 캐싱하는 플러그인
  cached_network_image: ^3.3.0
  # 인피니티 스크롤과 커스텀 차일드 위젯을 쉽게 쓸 수 있는 캐러셀 위젯
  carousel_slider: ^4.2.1
  # 오류 / 예외를 자동으로 포착하고 설정에 따라 보고하거나 기록하는 도구
  catcher_2: ^1.0.4
  # 실시간 동기화 noSQL 데이터베이스 Cloud Firestore용 Flutter 플러그인
  cloud_firestore: ^4.13.1
  # [Dart] dart:collection을 확장한 유틸리티 컬렉션
  collection: ^1.18.0
  # 네트워크 연결 상태 플러그인
  connectivity_plus: ^2.3.9
  # [Dart] 인터셉터, 요청 취소, 타임아웃, 어댑터, 트랜스포머, 폼데이터, 파일 업로드/다운로드 등을 지원하는 HTTP 패키지
  dio: ^5.3.3
  # 드롭다운 버튼
  dropdown_button2: ^2.3.9
  # 다국어 설정 및 언어 변경 간소화
  easy_localization: ^3.0.3
  # yaml,json,csv 등 다양한 파일 형식을 지원하는 다국어 플러그인
  easy_localization_loader: ^1.0.1+1
  # [Dart] equals 메소드 컨버터
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  # 플러터 애니메이션 효과
  flutter_animate: ^4.2.0+1
  # 플러터 환경변수 (.env) 플러그인
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  # 플러터 마크다운 위젯
  flutter_markdown: ^0.6.18+2
  # 플러터 네이티브 스플래시
  flutter_native_splash: ^2.3.5
  # 화면 및 글꼴 크기 조정: 다양한 화면 크기에 적합한 레이아웃 표시
  flutter_screenutil: ^5.9.0
  # 플러터 SVG 렌더러
  flutter_svg: ^2.0.9
  # 폰트어썸 아이콘 폰트 플러그인
  font_awesome_flutter: ^10.6.0
  # CSS 컬러 변환 플러그인
  from_css_color: ^2.0.0
  # 의존성 주입 모듈
  get_it: ^7.6.4
  # 고 라우터
  go_router: ^12.1.1
  # 구글 폰트
  google_fonts: ^4.0.4
  # 하이브 (크로스플랫폼 NoSQL DB)
  hive_flutter: ^1.1.0
  # Riverpod 훅
  # Riverpod 훅
  hooks_riverpod: ^2.4.6
  intl: ^0.18.1
  # [Dart] json_serializable에서 사용하는 어노테이션
  json_annotation: ^4.8.1
  # [Dart] JSON 데이터를 모델 클래스로 쉽게 변환해주는 빌드 러너 제너레이터
  json_serializable: ^6.7.1
  # [Dart] 가독성 좋은 로그 작성을 도와주는 로깅 도구
  logger: ^2.0.2+1
  # 로티.json 애니메이션
  lottie: ^2.7.0
  # 페이지 전환 패키지
  page_transition: ^2.1.0
  # 프로바이더 (상태관리)
  provider: ^6.1.1
  # 온보딩 스크린 등에 많이 쓰는 페이지 인디케이터
  smooth_page_indicator: ^1.1.0
  # URL 실행 도구
  url_launcher: ^6.2.1

dev_dependencies:
  analyzer: ^5.13.0
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.7
  dart_code_metrics: ^5.7.6
  flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  mockito: ^5.4.3

flutter:
  # 머티리얼 아이콘 폰트가 애플리케이션에 포함되어 있는지 확인하여 머티리얼 아이콘 클래스에서 아이콘을 사용할 수 있도록 함.
  uses-material-design: true
  generate: true
  # 애플리케이션에 에셋을 추가하려면 다음과 같이 에셋 섹션을 추가함:
  assets:
    - .env
    - assets/google_fonts/
    - assets/images/
    - assets/images/experts/
    - assets/images/tests/
    - assets/lotties/
    - assets/messages/
    - assets/svg/

  fonts:
    - family: Poppins
      # https://fonts.google.com/specimen/Poppins
    - family: Nanum Square Neo
      # https://hangeul.naver.com/font/nanum
      fonts:
        - asset: assets/fonts/NanumSquareNeo-Bold.ttf
        - asset: assets/fonts/NanumSquareNeo-ExtraBold.ttf
        - asset: assets/fonts/NanumSquareNeo-Heavy.ttf
        - asset: assets/fonts/NanumSquareNeo-Light.ttf
        - asset: assets/fonts/NanumSquareNeo-Regular.ttf

# flutter_gen_runner는 자산, 폰트, 색상 등을 위한 Flutter 코드 생성기로, 문자열 기반 API를 없애줌.
# String 기반으로 자산 경로를 사용하는 것은 안전하지 않음.
# build_runner와 FlutterGen을 패키지의 pubspec.yaml 파일에 추가하고,
# Homebrew 또는 Pub Global activate를 사용하여 FlutterGen CLI binary를 설치.
# https://pub.dev/packages/flutter_gen_runner
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    enabled: true
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors/palette.xml

# Usage:
#   dart run import_sorter:main -e
import_sorter:
  emojis: true

analyzer:
  errors:
    deprecated_member_use_from_same_package: ignore
    invalid_annotation_target: ignore
  exclude:
    - bin/cache/**
    - "**/*.g.dart"
    - "**/*.gen.dart"
    - "**/gen/*.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/injector.config.dart"
    - "**/test/*.dart"

# 아이콘 생성 원할 시, dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: assets/icons/cami.png
  ios: true
  remove_alpha_ios: false
  android: ic_launcher
  min_sdk_android: 21
  web:
    generate: true
  macos:
    generate: true

flutter_native_splash:
  color: "#FFFF50"
  image: assets/splash/splash.png
  branding: assets/splash/branding.png
  branding_mode: top
  android_gravity: bottom
  ios_content_mode: bottom
  web_image_mode: bottom
  android_12:
    image: assets/splash/splash.png
    color: "#FFFF50"
    branding: assets/splash/branding.png
