// 🌎 Project imports:
import '/data/models/check_up.dart';
import '/data/models/detail_image.dart';
import '/gen/assets.gen.dart';

final checkUpList = [
  CheckUp(
    description: '16가지의 성격 유형, 멍BTI로 내 강아지의 성격 바로 알기',
    detailImages: [
      DetailImage(imagePath: Assets.images.tests.dogDcsiIi01.path),
      DetailImage(imagePath: Assets.images.tests.dogDcsiIi02.path),
      DetailImage(imagePath: Assets.images.tests.dogDcsiIi03.path),
      DetailImage(imagePath: Assets.images.tests.dogDcsiIi04.path),
      DetailImage(imagePath: Assets.images.tests.dogDcsiIi05.path),
      DetailImage(imagePath: Assets.images.tests.dogDcsiIi06.path),
      DetailImage(imagePath: Assets.images.tests.dogDcsiIi07.path),
      DetailImage(imagePath: Assets.images.tests.dogDcsiIi08.path),
      DetailImage(imagePath: Assets.images.tests.dogDcsiIi09.path),
    ],
    featured: true,
    fullName: '반려견 성격유형검사 (DCSI-II)',
    location: '/checkup/dcsi-ii',
    nickname: '강아지 MBTI',
    popular: true,
    price: '9,000원',
    questions: 107,
    reviewRating: 4.9,
    reviewsCount: 916,
    duration: 20,
    short: 'DCSI-II',
    testname: '반려견 성격유형검사',
    thumbPath: Assets.images.thumbs.test14789.path,
    type: '반려견',
  ),
  CheckUp(
    description: '알쏭달쏭 고양이 성격 알아채기! 집사 전용 냥BTI',
    detailImages: [
      DetailImage(imagePath: Assets.images.tests.catCcsi01.path),
      DetailImage(imagePath: Assets.images.tests.catCcsi02.path),
      DetailImage(imagePath: Assets.images.tests.catCcsi03.path),
      DetailImage(imagePath: Assets.images.tests.catCcsi04.path),
      DetailImage(imagePath: Assets.images.tests.catCcsi05.path),
      DetailImage(imagePath: Assets.images.tests.catCcsi06.path),
      DetailImage(imagePath: Assets.images.tests.catCcsi07.path),
      DetailImage(imagePath: Assets.images.tests.catCcsi08.path),
      DetailImage(imagePath: Assets.images.tests.catCcsi09.path),
    ],
    featured: true,
    fullName: '반려묘 성격유형검사 (CCSI)',
    location: '/checkup/ccsi',
    nickname: '고양이 MBTI',
    popular: true,
    price: '12,000원',
    questions: 128,
    reviewRating: 4.9,
    reviewsCount: 86,
    duration: 20,
    short: 'CCSI',
    testname: '반려묘 성격유형검사',
    thumbPath: Assets.images.thumbs.test14791.path,
    type: '반려묘',
  ),
  CheckUp(
    description: '강아지와 함께할 준비 되셨나요? 입양 자격 검사 (반려인 면허 시험)',
    detailImages: [
      DetailImage(imagePath: Assets.images.tests.ownerDpai01.path),
      DetailImage(imagePath: Assets.images.tests.ownerDpai02.path),
      DetailImage(imagePath: Assets.images.tests.ownerDpai03.path),
      DetailImage(imagePath: Assets.images.tests.ownerDpai04.path),
      DetailImage(imagePath: Assets.images.tests.ownerDpai05.path),
      DetailImage(imagePath: Assets.images.tests.ownerDpai06.path),
    ],
    featured: false,
    fullName: '입양준비검사 (DPAI)',
    location: '/checkup/dpai',
    nickname: '보호자 양육면허시험',
    popular: false,
    price: '9,900원',
    questions: 84,
    reviewRating: 5,
    reviewsCount: 4,
    duration: 20,
    short: 'DPAI',
    testname: '입양준비검사',
    thumbPath: Assets.images.thumbs.test14794.path,
    type: '반려인',
  ),
  CheckUp(
    description: '위태로운 반려생활은 그만! 강아지 공격성 검사',
    detailImages: [
      DetailImage(imagePath: Assets.images.tests.dogDabi01.path),
      DetailImage(imagePath: Assets.images.tests.dogDabi02.path),
      DetailImage(imagePath: Assets.images.tests.dogDabi03.path),
      DetailImage(imagePath: Assets.images.tests.dogDabi04.path),
    ],
    featured: true,
    fullName: '반려견 위협행동검사 (DABI)',
    location: '/checkup/dabi',
    nickname: '강아지 공격성 검사',
    popular: false,
    price: '6,000원',
    questions: 15,
    reviewRating: 4.4,
    reviewsCount: 15,
    short: 'DABI',
    testname: '반려견 위협행동검사',
    thumbPath: Assets.images.thumbs.test14793.path,
    type: '반려견',
  ),
  CheckUp(
    description: '한 눈에 척! 알아보는 강아지 성격 분석',
    detailImages: [
      DetailImage(imagePath: Assets.images.tests.dogDaci.path),
    ],
    featured: false,
    fullName: '형용사 성격검사 (DACI)',
    location: '/checkup/daci',
    nickname: '강아지 형용사 성격검사',
    popular: false,
    price: '2,900원',
    questions: 32,
    reviewRating: 4.7,
    reviewsCount: 371,
    duration: 3,
    short: 'DACI',
    testname: '형용사 성격검사',
    thumbPath: Assets.images.thumbs.test14796.path,
    type: '반려견',
  ),
  CheckUp(
    description: '우리 모두 행복하기 위해, 반려인의 마음 건강 체크하기',
    detailImages: [
      DetailImage(imagePath: Assets.images.tests.ownerDds01.path),
      DetailImage(imagePath: Assets.images.tests.ownerDds02.path),
      DetailImage(imagePath: Assets.images.tests.ownerDds03.path),
      DetailImage(imagePath: Assets.images.tests.ownerDds04.path),
      DetailImage(imagePath: Assets.images.tests.ownerDds05.path),
    ],
    featured: false,
    fullName: '한국형 역기능 우울척도 (DDS)',
    location: '/checkup/dds',
    nickname: '보호자 마음건강 테스트',
    popular: false,
    price: '무료',
    questions: 20,
    reviewRating: 5,
    reviewsCount: 192,
    duration: 5,
    short: 'DDS',
    testname: '한국형 역기능 우울척도',
    thumbPath: Assets.images.thumbs.test14795.path,
    type: '반려인',
  ),
  CheckUp(
    description: '강아지 입장에서 바라보는 ‘나’는? 양육 능력 점검하기',
    detailImages: [
      DetailImage(imagePath: Assets.images.tests.ownerDopi01.path),
      DetailImage(imagePath: Assets.images.tests.ownerDopi02.path),
      DetailImage(imagePath: Assets.images.tests.ownerDopi03.path),
      DetailImage(imagePath: Assets.images.tests.ownerDopi04.path),
      DetailImage(imagePath: Assets.images.tests.ownerDopi05.path),
      DetailImage(imagePath: Assets.images.tests.ownerDopi06.path),
      DetailImage(imagePath: Assets.images.tests.ownerDopi07.path),
    ],
    featured: false,
    fullName: '양육자신감검사 (DOPI)',
    location: '/checkup/dopi',
    nickname: '반려인 양육능력 테스트',
    popular: false,
    price: '9,900원',
    questions: 154,
    reviewRating: 4.9,
    reviewsCount: 94,
    duration: 15,
    short: 'DOPI',
    testname: '양육자신감검사',
    thumbPath: Assets.images.thumbs.test14792.path,
    type: '반려인',
  ),
  CheckUp(
    description: '8세 이상 강아지 필수 검사, 치매 가능성 평가',
    detailImages: [
      DetailImage(imagePath: Assets.images.tests.dogCades01.path),
      DetailImage(imagePath: Assets.images.tests.dogCades02.path),
      DetailImage(imagePath: Assets.images.tests.dogCades03.path),
      DetailImage(imagePath: Assets.images.tests.dogCades04.path),
      DetailImage(imagePath: Assets.images.tests.dogCades05.path),
      DetailImage(imagePath: Assets.images.tests.dogCades06.path),
    ],
    featured: false,
    fullName: '반려견 인지장애검사 (CADES)',
    location: '/checkup/cades',
    nickname: '[무료] 강아지 치매검사',
    popular: false,
    price: '무료',
    questions: 17,
    reviewRating: 5,
    reviewsCount: 147,
    short: 'CADES',
    testname: '반려견 인지장애검사',
    thumbPath: Assets.images.thumbs.test14798.path,
    type: '반려견',
  ),
  CheckUp(
    description: '1년에 한 번은 정서건강 검진 타임, 강아지 마음 종합 검사',
    detailImages: [
      DetailImage(imagePath: Assets.images.tests.dogDobi01.path),
      DetailImage(imagePath: Assets.images.tests.dogDobi02.path),
      DetailImage(imagePath: Assets.images.tests.dogDobi03.path),
      DetailImage(imagePath: Assets.images.tests.dogDobi04.path),
      DetailImage(imagePath: Assets.images.tests.dogDobi05.path),
      DetailImage(imagePath: Assets.images.tests.dogDobi06.path),
      DetailImage(imagePath: Assets.images.tests.dogDobi07.path),
      DetailImage(imagePath: Assets.images.tests.dogDobi08.path),
      DetailImage(imagePath: Assets.images.tests.dogDobi09.path),
    ],
    featured: false,
    fullName: '반려견 정서행동검사 (DOBI)',
    location: '/checkup/dobi',
    nickname: '강아지 마음건강 종합검사',
    popular: true,
    price: '30,000원',
    questions: 186,
    reviewRating: 4.9,
    reviewsCount: 95,
    duration: 20,
    short: 'DOBI',
    testname: '반려견 정서행동검사',
    thumbPath: Assets.images.thumbs.test14797.path,
    type: '반려견',
  ),
];
